---
title: "Projekt 732G33"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

*Författare:* Elsa Lindgren och Emma Masterson.

*LiU-id:* elsli688 och emmma887

*Grupp:* 11

```{r, echo=FALSE}
# Lägg chunks med R-kod innan texten där ni laddar in data från internet

# kommentera er kod och ha god kodstil
```


# Introduktion
Här är det en introduktion. Beskriv era variabler mm.

# Kommundata

Gör delarna för kommundata här.

```{r, echo=FALSE}
# Lite kommentarer och beräkningar som inte syns sedan
a <- 1 + 5
```


```{r, echo=TRUE}
# Detta syns
1 + 5
```


Exempel på att skapa en graf:

```{r, echo=FALSE}
data(cars)
plot(cars)
```

Exempel på att skapa en tabell:

```{r, echo=FALSE}
library(knitr)
kable(head(cars))
```

# Tidseriedata

Gör delarna för tidseriedata här.

```{r, echo=FALSE}
data_url1 <- "https://raw.githubusercontent.com/elsalindgren/Projektarbete/refs/heads/main/skillsm%C3%A4ssor.txt"
skilsmässor <- read.table(data_url1)

library(ggplot2)
ggplot(data = skilsmässor) +
  geom_line(aes(x = as.Date(datum),
                y = skilsmässor,
                group = 1),
            linewidth = 1.01,
            color = "steelblue2") +
  scale_x_date(date_breaks = "1 year",
               date_labels = "%Y") +
  labs(y = "Antal skilsmässor",
       x = "År",
       caption = "Källa: SCB",
       title = "Skilsmässor per månad mellan 2005 och 2016")

```

```{r, echo=FALSE}
month_means <- aggregate(skilsmässor ~ månad, data = skilsmässor, FUN = mean)

etiketter <- month_means$månad[seq(1, 12, by = 1)]
month_pos <- 0:11
month_means[, 3] <- month_pos
names(month_means)[3] <- "month_pos"

ggplot(data = month_means) +
  geom_col(aes(x = month_pos,
               y = skilsmässor),
           color = "darkblue",
           fill = "steelblue2") +
  labs(y = "Skilsmässor",
       x = "Månad",
       caption = "Källa: SCB",
       title = "Genomsnittligt antal skilsmässor per månad") +
  scale_y_continuous(breaks = seq(0, 3500, 500),
                     limits = c(0, 3500)) +
  scale_x_continuous(labels = etiketter,
                     breaks = seq(0, 11, 1))
```


```{r, echo=FALSE}



```






